---
title: "model_fitting"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{model_fitting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(bioinactivation2)
```

## The `fit_inactivation()` function

AA

## Fitting primary models

```{r}
data("inactivation_experiment")

make_guess_primary(inactivation_experiment, 
                   "Geeraerd", formula = logN ~ t)


check_inactivation_guess("primary", 
                         inactivation_experiment, 
                         "Geeraerd",
                         make_guess_primary(inactivation_experiment,
                                            "Geeraerd", 
                                            formula = logN ~ t),
                         formula = logN ~ t
                         )


# guess <- list(logN0 = 8, logD = 2)
known <- list()

aa <- fit_inactivation("primary", 
                       inactivation_experiment, 
                       "Bigelow",
                       make_guess_primary(inactivation_experiment, 
                                          "Bigelow", formula = logN ~ t), 
                       known,
                       formula = logN ~ t)
coef(aa)
summary(aa)
plot(aa)
```

```{r}
## with bounds

fit_inactivation("primary", 
                       inactivation_experiment, 
                       "Bigelow",
                       guess = c(logN0 = 8, logD = 0.3), 
                       # known = c(),
                 lower = c(logN0 = 7, logD = .1),
                 upper = c(logN0 = 9, logD = .4),
                       formula = logN ~ t) %>% 
  summary()
```
## Other algorithm 

```{r}

aa <- fit_inactivation("primary", 
                       inactivation_experiment, 
                       "Bigelow",
                       make_guess_primary(inactivation_experiment, 
                                          "Bigelow", formula = logN ~ t), 
                       algorithm = "MCMC",
                       formula = logN ~ t,
                       niter = 100,
                       burninlength = 20)
coef(aa)
summary(aa)
plot(aa)
```



```{r}
guess <- list(logN0 = 8, logD = 2)
known <- list()

aa <- fit_inactivation("primary", inactivation_experiment, "Bigelow", guess, known,
                       formula = logN ~ t)
summary(aa)
plot(aa)
```

```{r}
guess <- list(logN0 = 8, delta = 1, p = 1)
known <- list()

aa <- fit_inactivation("primary", inactivation_experiment, "Mafart", guess, known,
                       formula = logN ~ t)
summary(aa)
plot(aa)
```

```{r}
fit_inactivation("primary", inactivation_experiment, "Peleg",
                       make_guess_primary(inactivation_experiment, "Peleg",
                                          formula = logN ~ t), 
                 known = c(),
                 formula = logN ~ t) %>%
  plot()
```


## Dynamic fitting

```{r}
data("dynamic_conditions")
data("dynamic_experiment")

sec_models <- list(
  list(par = "D",
       model = "Bigelow",
       depends_on = c("temp", "pH")
  )
)

guess <- c(logN0 = 7,
           D_temp_logz = .69,
           D_pH_z = 2,
           D_logref = 1
)

known <- c(D_temp_xref = 55,
           D_pH_xref = 7
           )


check_inactivation_guess("dynamic", 
                         dynamic_experiment,
                         primary_model_name = "Bigelow",
                         c(guess, known),
                         secondary_models = sec_models,
                         env_conditions = dynamic_conditions
                         )

aa <- fit_inactivation("dynamic", 
                 dynamic_experiment, 
                 "Bigelow",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = dynamic_conditions,
                 algorithm = "regression")

plot(aa)
summary(aa)


```

```{r}

## Bounds

fit_inactivation("dynamic", 
                 dynamic_experiment, 
                 "Bigelow",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = dynamic_conditions,
                 algorithm = "regression",
                 upper = c(logN0 = 8, D_temp_logz = 1, D_pH_z = 3, D_logref = 2),
                 lower = c(logN0 = 4, D_temp_logz = 0, D_pH_z = 1, D_logref = 0)
                 ) %>%
  summary()
```

```{r}
## Algorithm

aa <- fit_inactivation("dynamic", 
                 dynamic_experiment, 
                 "Bigelow",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = dynamic_conditions,
                 algorithm = "MCMC",
                 niter = 100,
                 burninlength = 50)

summary(aa)
plot(aa)

```

```{r}
data("dynamic_experiment")

env_conditions <- tibble(time = c(0, 3, 5),
                         temp = c(55, 60, 55))

sec_models <- list(
  list(par = "D",
       model = "Bigelow",
       depends_on = c("temp")
  ),
  list(
    par = "c",
    model = "Bigelow",
    depends_on = c()
  ),
  list(
    par = "k",
    model = "kAcclimation",
    depends_on = c("temp")
  )
)

guess <- c(logN0 = 7,
           c_ref = 8,
           k_temp_E = .01, 
           k_ref = .1
)

known <- c(D_temp_xref = 55,
           D_temp_z = 5,
           D_logref = 1,
           p0 = 1e-6,
           k_temp_Xsi = 30
)


check_inactivation_guess("dynamic", 
                         dynamic_experiment,
                         primary_model_name = "Acclimation",
                         c(guess, known),
                         secondary_models = sec_models,
                         env_conditions = env_conditions
)

bb <- fit_inactivation("dynamic", 
                       dynamic_experiment, 
                       "Acclimation",
                       guess, 
                       known, 
                       lower = c(logN0 = 6,
                                 c_ref = 6,
                                 k_temp_E = .001, 
                                 k_ref = .01),
                       upper = c(logN0 = 8,
                                 c_ref = 9,
                                 k_temp_E = .1, 
                                 k_ref = 1
                                 ),
                       secondary_models = sec_models,
                       env_conditions = env_conditions,
                       algorithm = "regression")#,
                       # niter = 1000)

plot(bb)
summary(bb)
```


## One-step fit

```{r}

data("inactivation_onestep")

sec_models <- list(
  list(par = "delta",
       model = "Bigelow",
       depends_on = c("temp", "pH")
  ),
  list(par = "p",
       model = "Bigelow",
       depends_on = c()
  )
)

guess <- c(logN0 = 7,
           delta_temp_logz = .69,
           delta_pH_z = 2,
           delta_logref = 1,
           p_logref = 0
)

known <- c(delta_temp_xref = 55,
           delta_pH_xref = 7
           )


aa <- fit_inactivation("one-step", 
                 inactivation_onestep, 
                 "Mafart",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = env_conditions,
                 algorithm = "regression")

summary(aa)
plot(aa)
```

```{r}

## bounds

fit_inactivation("one-step", 
                 inactivation_onestep, 
                 "Mafart",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = env_conditions,
                 algorithm = "regression",
                 upper = c(logN0 = 8, delta_temp_logz = 1, delta_pH_z = 3,
                           delta_logref = 2, p_logref = 1),
                 lower = c(logN0 = 6, delta_temp_logz = -1, delta_pH_z = .5,
                           delta_logref = 0, p_logref = -1)
                 ) %>%
  summary()
```

```{r}
aa <- fit_inactivation("one-step", 
                 inactivation_onestep, 
                 "Mafart",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = env_conditions,
                 algorithm = "MCMC",
                 niter = 10)

summary(aa)
plot(aa)
```


## Fitting secondary models - the `fit_inactivation_secondary()` function

```{r}
##

data("inactivation_secondary")

make_guess_secondary(inactivation_secondary, "genBigelow", formula = delta ~ temp + pH)

check_secondary_guess(inactivation_secondary, "genBigelow", 
                      make_guess_secondary(inactivation_secondary, "genBigelow", 
                                           formula = delta ~ temp + pH),
                      formula = delta ~ temp + pH
                      )

guess <- c(temp_logz = .69,
           pH_z = 2,
           logref = 1
)

known <- c(temp_xref = 55,
           pH_xref = 7
)

aa <- fit_inactivation_secondary(inactivation_secondary,
                           "Bigelow",
                           guess = guess,
                           known = known,
                           formula = delta ~ temp + pH
)

coef(aa)
summary(aa)

check_secondary_guess(inactivation_secondary, "Bigelow", 
                      c(coef(aa), known),
                      formula = delta ~ temp + pH
                      )

predict(aa)
predict(aa, newdata = tibble(temp = c(55, 56), pH = c(7, 5)))
plot(aa)
plot(aa, type = 2)
```

```{r}
# bounds

guess <- c(temp_logz = .69,
           pH_z = 2,
           logref = 1
           )

upper <- c(temp_logz = .75,
           pH_z = 2.5,
           logref = 2
           )


lower <- c(temp_logz = .2,
           pH_z = 0,
           logref = 0
           )


aa <- fit_inactivation_secondary(inactivation_secondary,
                           "Bigelow",
                           guess = guess,
                           known = known,
                           formula = delta ~ temp + pH,
                           upper = upper,
                           lower = lower
)

summary(aa)
```

```{r}
## MCMC

aa <- fit_inactivation_secondary(inactivation_secondary,
                           "Bigelow",
                           guess = guess,
                           known = known,
                           formula = delta ~ temp + pH,
                           algorithm = "MCMC",
                           niter = 10
                           )

summary(aa)
```

## Global fitting

```{r}

data("multiple_counts")
data("multiple_environments")

sec_models <- list(
  list(par = "D",
       model = "Bigelow",
       depends_on = c("temp", "pH")
  )
)

guess <- c(logN0 = 7,
           D_temp_logz = .69,
           D_pH_z = 2,
           D_logref = 1
)

known <- c(D_temp_xref = 55,
           D_pH_xref = 7
           )


check_inactivation_guess("global",
                         fit_data = multiple_counts,
                         "Bigelow",
                         c(guess, known),
                         secondary_models = sec_models,
                         env_conditions = multiple_environments
                         )

aa <- fit_inactivation("global", 
                 multiple_counts, 
                 "Bigelow",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = multiple_environments,
                 algorithm = "regression")

summary(aa)
```

```{r}
## bounds

aa <- fit_inactivation("global", 
                 multiple_counts, 
                 "Bigelow",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = multiple_environments,
                 algorithm = "regression",
                 upper = c(logN0 = 8, D_temp_logz = .8, D_pH_z = 4, D_logref = 2),
                 lower = c(logN0 = 6, D_temp_logz = .3, D_pH_z = 2, D_logref = 0)
                 )

summary(aa)
plot(aa)
```
### MCMC

```{r}
 bb <- fit_inactivation("global", 
                 multiple_counts, 
                 "Bigelow",
                 guess, 
                 known, 
                 secondary_models = sec_models,
                 env_conditions = multiple_environments,
                 algorithm = "MCMC",
                 niter = 10)
summary(bb)
plot(bb)
```


## Two-steps fitting

```{r}

data("inactivation_twosteps")


primary_model <- list(model = "Mafart", 
                      logN0 = 7
)

sec_models <- list(
  list(par = "delta",
       model = "Bigelow",
       depends_on = c("temp", "pH")
  ),
  list(par = "p",
       model = "Bigelow",
       depends_on = c()
  )
)

known <- c(delta_temp_xref = 55,
           delta_pH_xref = 7
           )

aa <- fit_inactivation("two-steps", 
                 inactivation_twosteps, 
                 "Mafart",
                 known = known, 
                 secondary_models = sec_models,
                 env_conditions = env_conditions,
                 algorithm = "regression")

coef(aa)
coef(aa, step = 1)
summary(aa)
summary(aa, step = 1)

```

```{r}
## fixing pars of the primary model

primary_model <- list(model = "Mafart", 
                      logN0 = 7
)

sec_models <- list(
  list(par = "delta",
       model = "Bigelow",
       depends_on = c("temp", "pH")
  )
  # list(par = "p",
  #      model = "Bigelow",
  #      depends_on = c()
  # )
)

known <- c(delta_temp_xref = 55,
           delta_pH_xref = 7,
           # logN0 = 7,
           p = .8
)

aa <- fit_inactivation("two-steps", 
                       inactivation_twosteps, 
                       "Mafart",
                       known = known, 
                       secondary_models = sec_models,
                       env_conditions = env_conditions,
                       algorithm = "regression")

summary(aa)
```





